[package]
name = "explainer_web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = { version = "0.21", features = ["csr"] }
gloo = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
